modLoader="javafml"
loaderVersion="[2,)"
license="MIT License"

[[mods]]
modId="just_ctgui"
version="0.0.55"
displayName="Just CTGUI"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="300f20t, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.just_ctgui]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.just_ctgui]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"




[[mixins]]
    config="mixins.just_ctgui.json"