modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="recipe_generator"
version="0.3.0"
displayName="Recipe Generator"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="300f20t, MCreator"
description="The Just Craft Tweaker GUI mod provides a visual recipe editor in minecraft using Craft Tweaker and a simple Zen Script programming language."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.recipe_generator]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.92,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.recipe_generator]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration